// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtbgayqzjrxjjmsjikcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10YmdheXF6anJ4amptc2ppa2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODM1MjIsImV4cCI6MjA1Mzc1OTUyMn0.JhsgQ7N-vJEDdJrNJc631cNu5sKe_RvWmq5pSLEPvOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);